### DISCUSSION TITLE
iopool in HomeAssistant

### DISCUSSION THREAD

**Discussion by Pharizna** [iopool/community#14] [Q&A] [answered]
Hi 
I'm trying to connect my new iopool to HomeAssistant creating a new sensor,,,

`sensor:
  - platform: rest
    name: iopool
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json.id }}"
    headers:
      x-api-key: {myAPI}
`

but it doesn't work.
There is not any sintax  error ... but  in the LOG file only appears the message:

[homeassistant.helpers.template] Template variable warning: 'list object' has no attribute 'id' when rendering '{{ value_json.id }}'

and not any info in the sensor.iopool .

Trying wthh the "full" JSON (value_json)  appears a message about >255 characters :(

Thank you in advance for your help

**Comment by mehdyouras** [comment]
Hello, thanks for your interest in the iopool public api. 
Here you're using the `/pools` path which returns a comprehensive list of your pools. That's why you cannot access the id with `{{ value_json.id }}` it should be `{{ value_json[0].id }}` (for the first pool).

If you want to get only one pool. You should get all your pools and get the id of the pool you're interested in. Then make a call to the route `/pool/{id}`. This way you could use `{{ value_json.id }}`.

Hope it helps.

**Reply by Pharizna** [reply]
Thank you

With the attached code works

`sensor:
  - platform: rest
    name: iopool_t
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json[0].latestMeasure.temperature }} "
    headers:
      x-api-key:  {myAPI}

  - platform: rest
    name: iopool_ph
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json[0].latestMeasure.ph  }} "
    headers:
      x-api-key:  {myAPI}

  - platform: rest
    name: iopool_orp
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json[0].latestMeasure.orp }} " 
    headers:
      x-api-key:  {myAPI}

`
But I need to format them as decimal numbers ... and I don't know yet :(

![iopool](https://user-images.githubusercontent.com/3939655/186483707-99f76964-6fca-44f3-8dfb-07fe3c0e8345.jpg)

**Reply by mehdyouras** [reply]
I'm glad that it works for you now. Unfortunately I've never used HomeAssistant so I won't be able to help you with this.

**Reply by ReenigneArcher** [reply]
Here is how you can format the decimal places (and units).

```yml
- platform: rest
  name: iopool_temperature
  resource: https://api.iopool.com/v1/pools
  unit_of_measurement: '°F'
  value_template: "{{ (value_json[0].latestMeasure.temperature * 9 / 5 + 32) | int }} "
  headers:
    x-api-key: !secret iopool_api_key

- platform: rest
  name: iopool_ph
  resource: https://api.iopool.com/v1/pools
  unit_of_measurement: 'pH'
  value_template: "{{'%0.1f' | format(value_json[0].latestMeasure.ph) }} "
  headers:
    x-api-key: !secret iopool_api_key

- platform: rest
  name: iopool_orp
  resource: https://api.iopool.com/v1/pools
  unit_of_measurement: 'mV'
  value_template: "{{ value_json[0].latestMeasure.orp }} "
  headers:
    x-api-key: !secret iopool_api_key
```

**Comment by Jeoffreybauvin** [comment]
Maybe you need to ask thisto Home Assistant community 😉

**Reply by Pharizna** [reply]
Don't worry!

Now it's working

`sensor:
  - platform: rest
    name: pool_t
    resource: https://api.iopool.com/v1/pools
    value_template: '{{ value_json[0].latestMeasure.temperature|round(1) }}'
    headers:
      x-api-key: {myAPI}
    unit_of_measurement : C


  - platform: rest
    name: pool_ph
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json[0].latestMeasure.ph  | round(1) }} "
    headers:
      x-api-key: {myAPI}
    unit_of_measurement : pH


  - platform: rest
    name: pool_orp
    resource: https://api.iopool.com/v1/pools
    value_template: "{{ value_json[0].latestMeasure.orp |  round(0) }} " 
    headers:
      x-api-key: {myAPI}
    unit_of_measurement : mV
`

![pool](https://user-images.githubusercontent.com/3939655/187085840-1365b4b4-75f7-4133-bc8f-fae916d68de7.jpg)

**Reply by jeff0077** [reply]
i want to use your configuration but i have this error
Invalid config for [sensor.rest]: expected a dictionary for dictionary value @ data['headers']. Got None
extra keys not allowed @ data['x-api-key']. Got OrderedDict([('myAPI', None)]). (See ?, line ?).

can you help me please

**Reply by jeff0077** [reply]
hi, It work fine now, can you said me witch card you for lovelace

**Reply by Pharizna** [reply]
For example, a gauge one like this one

```
type: gauge
entity: sensor.pisci1_orp
unit: mV
needle: true
min: 450
max: 1100
segments:
  - from: 450
    color: '#db4437'
  - from: 550
    color: '#ffa600'
  - from: 650
    color: '#43a047'
  - from: 850
    color: '#ffa600'
  - from: 1000
    color: '#db4437'
name: ' '
```
![274FE8E4-C1B6-41D6-AF9B-69090B7790FA](https://user-images.githubusercontent.com/3939655/203076958-0de8a841-bfc0-4e8d-83da-5ee917d53460.png)

**Reply by Conterganer** [reply]
bad indentation of a mapping entry (4:7)

 1 |   - sensor:
 2 |   
 3 |         platform: rest
 4 |       - name: "iopool_t"
-----------^
 5 |         resource: https://api.iopool.c ...
 6 |         value_template: "{{ value_json ...

```
  - sensor:
  
        platform: rest
      - name: "iopool_t"
        resource: https://api.iopool.com/v1/pools
        value_template: "{{ value_json[0].latestMeasure.temperature }} "
        headers:
        x-api-key: {xxxxxT}
        unit_of_measurement : C
        
        platform: rest
      - name: "iopool_ph"
        resource: https://api.iopool.com/v1/pools
        value_template: "{{ value_json[0].latestMeasure.ph }} "
        headers:
        x-api-key: {xxxxxxT}
        unit_of_measurement : pH
        
        platform: rest
      - name: "iopool_orp"
        resource: https://api.iopool.com/v1/pools
        value_template: "{{ value_json[0].latestMeasure.orp }} "
        headers:
        x-api-key: {xxxxxxT}
        unit_of_measurement : mV
```

**Comment by Pharizna** [comment, marked as answer]
Hi
You have to write your APIkey instead “myAPI”.


For example, in my case is something similar to this one:

headers:
      x-api-key: LxRWs9u9OwaX0e53cgS5u5OdnAKerNh…
    scan_interval: 60

you have to ask for your APIkey to iopool people

Also, you have to remember that It is a YAML file and you have to ‘indent’ the code lines
![6D74B396-E63A-48D9-A364-EAF92B0BC916](https://user-images.githubusercontent.com/3939655/202860339-78453114-e7f0-4b51-908c-f1c6aaffe6e2.png)

**Reply by jeff0077** [reply]
Thanks, i'm asking to the support an api key and after i'm testing

**Reply by Conterganer** [reply]
Den APIkey habe ich hier durch xxxxxxT
I have the APIkey here through

**Reply by Jeoffreybauvin** [reply]
Please, hide your API KEY :(.

**Reply by Pharizna** [reply]
@Conterganer You are using a bad indentation :(

The correct one is:

![image](https://github.com/iopool/community/assets/3939655/14c42926-bc7b-4f06-8a53-5e06638b9bfa)

**Comment by mguyard** [comment]
Bonjour à tous,

Après mon plugin sur Jeedom, je vous propose mon tuto pour HA : https://forum.hacf.fr/t/tuto-gestion-de-sa-piscine-avec-sonde-iopool/24292

-----

Hello,

After my Jeedom plugin, here is my tutorial for HA : https://forum.hacf.fr/t/tuto-gestion-de-sa-piscine-avec-sonde-iopool/24292
It's in french but i think you can use a translate tool ;)

**Reply by RRoyceus** [reply]
I have Home Assistant.  I would like to install this addon to Home Assistant, but I don't have any idea how to start.  Can anyone help me.  If it matters, I have HACS, file editor, and terminal installed.

I will gladly pay somebody to help. My end goal is to use HA to send the values to an ISY

**Reply by mguyard** [reply]
Hello,

It's not an addon. You only need to follow my tutorial (link in my previous message)

**Reply by theo1oo** [reply]
Hi mguyard,

i followed your Tutorial using the browser translation to german. So far it works, except for the part with the filtraion inteligence using app daemon. I didn't implemented it yet, because i don't know how exactly your filtration works. Could you please explain why do you have two timeslots for filtration. And how it works. Until now i have an fixed timeslot of 7 hours a day in the afternoon, and beforehand the pump can run whenever enough Power from my PV System is available

**Comment by RRoyceus** [comment]
Marc,

Many thanks for your fast reply.   Before my post, I had tried repeatedly to open both your links.  I had click on both and copied and pasted in a new window.  Each time , the link times out.  Any idea how i can get your instructions some other way?  Maybe post the instructions????  Once again, many thanks.

Best Regards,

Jimmy Scruggs
Office 713-649-2776 x 6
Mobile: 713-899-1862

On Jun 28, 2023, at 11:57 PM, Marc GUYARD ***@***.***> wrote:

﻿

Hello,

It's not an addon. You only need to follow my tutorial (link in my previous message)

—
Reply to this email directly, view it on GitHub<https://github.com/iopool/community/discussions/14#discussioncomment-6311280>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIC6L6242M236QXFDJTZTA3XNUDMFANCNFSM57MGSJ7A>.
You are receiving this because you commented.Message ID: ***@***.***>




________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us1.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=1688014659-3U6uqGc46abK&r_address=jscruggs%40scruggsco.com&report=1> to report this email as spam.

**Reply by RRoyceus** [reply]
Marc,

Many thanks for your fast reply.   Before my post, I had tried repeatedly to open both your links.  I had click on both and copied and pasted in a new window.  Each time , the link times out.  Any idea how i can get your instructions some other way?  Maybe post the instructions????  Once again, many thanks.

**Comment by mguyard** [comment]
Link can be open on my side
<img width="839" alt="CleanShot 2023-06-29 at 08 35 22@2x" src="https://github.com/iopool/community/assets/5262395/ae2ad41d-71dd-4a71-b08f-3b017369aeb6">

So you need to look why you can't access to it on your side.
I don't want to share here as i don't want to have to manage tutorial on multiple place.

**Comment by RRoyceus** [comment]
Anybody want to make $250?  Back ground is I am 72 years old, have COPD, and on a breathing machine.  I have a salt water pool and it needs acid added daily to keep it in the proper range.  I can not safely handle acid.  I have 4 Raspberry PI’s set up as web servers. I have programmed in many languages, but at this point in my life, I am tired of learning.
 I can “mess around” in a Raspberry Pi, but getting this one working in Home Assistant is beyond my capabilities. After 2 weeks of trying, I give up.

 I have a Universal Devices - ISY / Polisy.   I designed, built, and programmed a CAI WebControl PLC, hooked up PH and ORP probes to read the values.  My system works.  Well it mostly works, but need constant tinkering.  I programmed the PLC to send the values to the ISY.  That works.  I wrote an ISY program that reads the values and turns on the acid pump as needed.  That works.

But I want a simpler system.  I installed Home Assistant in a PI. HA is an ISY plug in.
 I have the Iopool monitor.  I would like somebody that will Install HA on a SD card, add the code in my prior post, install the ISY add on, add the link needed to pass the PH, ORP, and Temp to the ISY, and finally send me the SD card.  I will pay through PayPal.

**Comment by ReenigneArcher** [comment]
Made some improvements to the info here. Hope it's useful to someone.

Using `rest` you can make a single http call and populate multiple entities. Also, pulling in some additional properties from the API (pool title, mode, action required, and filtration duration recommendation)

```yml
rest:
  - resource: "https://api.iopool.com/v1/pools"
    headers:
      x-api-key: !secret iopool_api_key
    sensor:
      - name: iopool_title
        icon: mdi:pool
        value_template: "{{ value_json[0].title }}"

      - name: iopool_mode
        icon: mdi:pool
        value_template: "{{ value_json[0].mode }}"

      - name: iopool_action_required
        icon: mdi:alert-box
        value_template: "{{ value_json[0].hasAnActionRequired }}"

      - name: iopool_temperature
        icon: mdi:pool-thermometer
        unit_of_measurement: '°F'
        value_template: "{{ (value_json[0].latestMeasure.temperature * 9 / 5 + 32) | int }}"  # degrees F
        # value_template: "{{'%0.1f' | format(value_json[0].latestMeasure.temperature) }}"  # degrees C

      - name: iopool_ph
        icon: mdi:ph
        unit_of_measurement: 'pH'
        value_template: "{{'%0.1f' | format(value_json[0].latestMeasure.ph) }}"

      - name: iopool_orp
        icon: mdi:scale-balance
        unit_of_measurement: 'mV'
        value_template: "{{ value_json[0].latestMeasure.orp }}"

      - name: iopool_filtration_duration_advice
        icon: mdi:pump
        unit_of_measurement: 'h'
        value_template: "{{ value_json[0].advice.filtrationDuration }}"
```

I'm not the best at setting up cards, but here's what I have after my first day playing with this.

![image](https://github.com/iopool/community/assets/42013603/791ae768-4906-42e2-9aaf-6455c34fd264)

Conditional card:
```yml
card:
  content: >-
    <font color="orange"><center><h2>Pool requires attention,<br>check iopool
    app.</h2></center></font>
  type: markdown
conditions:
  - entity: sensor.iopool_action_required
    state: 'True'
type: conditional
view_layout:
  position: sidebar
```

Auto entities card:
```yml
type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - name: iopool*
  exclude: []
```

Vertical stack in card water temp:
```yml
type: vertical-stack
cards:
  - graph: line
    type: sensor
    entity: sensor.iopool_temperature
    detail: 2
    name: Water temperature
    icon: ''
  - type: gauge
    entity: sensor.iopool_temperature
    segments:
      - from: 0
        color: '#db4437'
      - from: 59
        color: '#ffa600'
      - from: 69
        color: '#43a047'
      - from: 84
        color: '#ffa600'
      - from: 90
        color: '#db4437'
    min: 50
    max: 100
    needle: true
    name: Water Temperature
  - type: history-graph
    entities:
      - entity: sensor.iopool_temperature
```

Vertical stack in card ph:
```yml
type: vertical-stack
cards:
  - graph: line
    type: sensor
    entity: sensor.iopool_ph
    detail: 2
    icon: ''
    name: pH
  - type: gauge
    entity: sensor.iopool_ph
    segments:
      - from: 0
        color: '#db4437'
      - from: 6.8
        color: '#ffa600'
      - from: 7.1
        color: '#43a047'
      - from: 7.7
        color: '#ffa600'
      - from: 8.1
        color: '#db4437'
    min: 6.4
    max: 8.4
    needle: true
    name: pH
  - type: history-graph
    entities:
      - entity: sensor.iopool_ph
```


Vertical stack in card orp:
```yml
type: vertical-stack
cards:
  - graph: line
    type: sensor
    entity: sensor.iopool_orp
    detail: 2
    name: Disinfection potential
    icon: ''
  - type: gauge
    entity: sensor.iopool_orp
    segments:
      - from: 0
        color: '#db4437'
      - from: 550
        color: '#ffa600'
      - from: 650
        color: '#43a047'
      - from: 800
        color: '#ffa600'
      - from: 1000
        color: '#db4437'
    min: 350
    max: 1100
    needle: true
    name: Disinfection potential
  - type: history-graph
    entities:
      - entity: sensor.iopool_orp
```
